namespace Direwolf.Definitions;

public readonly record struct PerformanceIndicators(
    int ApplicationLoadTime,
    int DocumentLoadTime,
    int ResponseTimeAverage,
    int ViewChangeTimeAverage,
    int DocumentPrintingTimeAverage,
    int DocumentSyncTimeAverage,
    int DocumentSavingTimeAverage,
    int ElementDuplicationTimeAverage,
    int FailureProcessingEvents,
    int FileExportTimeAverage,
    int FileImportTimeAverage,
    int LinkedResourceLoadTimeAverage,
    int ProgressBarTimeAverage,
    int ViewExportTimeAverage,
    int ViewPrintTimeAverage,
    double FileSize,
    int FamilyCount,
    int WarningCount,
    int ViewsInsideDocument,
    int ViewsNotInSheets,
    int AnnotativeElementCount,
    int ExternalReferenceCount,
    int ModelGroupCount,
    int DetailGroupCount,
    int DesignGroupCount,
    int LevelCount,
    int GridCount,
    int UnenclosedRoomCount,
    int ViewportCount,
    int UnconnectedDuctCount,
    int UnconnectedPipeCount,
    int UnconnectedElectricalCount,
    int NonNativeStyleCount,
    int FlippedElementCount,
    int WorksetCount)
{
}